---
title: "data_clean"
author: "randy"
date: "8/2/2020"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(tidyverse)
library(stringr)

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

starbucks = read.csv('./data/starbucks2.csv', stringsAsFactors=FALSE)



```



```{r}
starbucks$store_count = rep(1, dim(starbucks)[1])

star1= starbucks%>% 
  select(c(-Postcode, -Phone.Number))
  
head(star1)
```

```{r}
code = read.csv('./data/country_code.csv')

code= code%>% 
  mutate(Country_Name= word(Country_Name, 1, sep=','))

code = code %>% 
  mutate(Country_Name= ifelse(Country_Name=='Azerbaijan' & Continent_Name=='Asia', '', Country_Name)) %>% 
  mutate(Country_Name= ifelse(Country_Name=='Georgia' & Continent_Name=='Asia', '', Country_Name)) %>% 
  mutate(Country_Name= ifelse(Country_Name=='Kazakhstan' & Continent_Name=='Asia', '', Country_Name)) %>% 
  mutate(Country_Name= ifelse(Country_Name=='Russian Federation' & Continent_Name=='Asia', '', Country_Name)) %>% 
  mutate(Country_Name= ifelse(Country_Name=='Armenia' & Continent_Name=='Asia', '', Country_Name)) %>% 
mutate(Country_Name= ifelse(Country_Name=='Korea' , 'South Korea',Country_Name)) %>% 
  mutate(Country_Name= ifelse(Country_Name=='United States of America' , 'United States',Country_Name))



code = code %>% 
  filter(Country_Name != 'NULL')

code= rename(code, continent= 'Continent_Name', 
             Country= 'Two_Letter_Country_Code')

code = code %>% 
  filter(Country_Name != '')


head(code, 5)

```


```{r}
#Merge code and starbucks so we can have a complete for the country
star2= full_join(star1, code, by='Country')

star3= star2 %>% 
  mutate(store_count= ifelse(is.na(store_count), 0, store_count))

names(star3) = tolower(names(star3))

star3= rename(star3, code= 'country',
                   country ='country_name')


```


```{r}
data1 = read.csv('./data/urban_pop.csv', encoding="UTF-8", stringsAsFactors=FALSE)

data1 = rename(data1, "country"=X.U.FEFF.country)

star4=left_join(star3, data1, by='country')
head(star1)
```


```{r}
data2 = read.csv('./data/gdp_per_capita.csv', encoding="UTF-8", stringsAsFactors=FALSE)

data2 = rename(data2, "country"=X.U.FEFF.country)
head(data2)
```


```{r}
star5=left_join(star4, data2, by='country')

head(star5)

```



```{r}
data3 = read.csv('./data/business.csv', encoding="UTF-8", stringsAsFactors=FALSE)

data3 = rename(data3, "country"=X.U.FEFF.country)


star6=left_join(star5, data3, by='country')

head(star6)

```
```{r}
data4 = read.csv('./data/median.csv', encoding="UTF-8", stringsAsFactors=FALSE)

star7=left_join(star6, data4, by='country')

```



```{r}
write.csv(star7, "./data/star.csv")
```

```{r}
revenue= read.csv("./data/revenue.csv", encoding = 'UTF-8', stringsAsFactors = F)

revenue = rename(revenue, year="X.U.FEFF.year")

write.csv(revenue, "./data/revenue.csv")
```

